"""indexes for the interface sort presets

Revision ID: 65b292dddfe2
Revises: 64e373ce205a
Create Date: 2026-09-14 17:00:21.735923+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "65b292dddfe2"
down_revision: str | None = "64e373ce205a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "catalog_product_name_wb_idx",
        "catalog_product",
        [sa.literal_column('name COLLATE "en_US.utf8" ASC'), sa.literal_column("wb_id ASC")],
        unique=False,
    )
    op.create_index(
        "catalog_product_price_wb_idx",
        "catalog_product",
        [sa.literal_column("price ASC"), sa.literal_column("wb_id ASC")],
        unique=False,
    )
    op.create_index(
        "catalog_product_rating_reviews_wb_idx",
        "catalog_product",
        [
            sa.literal_column("rating DESC"),
            sa.literal_column("reviews_count DESC"),
            sa.literal_column("wb_id ASC"),
        ],
        unique=False,
    )
    op.create_index(
        "catalog_product_reviews_wb_idx",
        "catalog_product",
        [sa.literal_column("reviews_count DESC"), sa.literal_column("wb_id ASC")],
        unique=False,
    )
    op.create_index(
        "catalog_product_saleprice_rating_wb_idx",
        "catalog_product",
        [
            sa.literal_column("sale_price ASC"),
            sa.literal_column("rating DESC"),
            sa.literal_column("wb_id ASC"),
        ],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Every migration must be reversible: a rollback that cannot undo the
    # schema is not a rollback.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("catalog_product_saleprice_rating_wb_idx", table_name="catalog_product")
    op.drop_index("catalog_product_reviews_wb_idx", table_name="catalog_product")
    op.drop_index("catalog_product_rating_reviews_wb_idx", table_name="catalog_product")
    op.drop_index("catalog_product_price_wb_idx", table_name="catalog_product")
    op.drop_index("catalog_product_name_wb_idx", table_name="catalog_product")
    # ### end Alembic commands ###
