# Generated by Django 5.2.17 on 2026-08-22 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRuleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("kind", models.CharField(max_length=16)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("channel", models.CharField(max_length=16)),
                ("target_wb_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                (
                    "target_query",
                    models.CharField(blank=True, db_index=True, max_length=200, null=True),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_alert_rule",
            },
        ),
        migrations.CreateModel(
            name="AlertEventModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("wb_id", models.BigIntegerField()),
                ("triggered_at", models.DateTimeField()),
                ("delivered", models.BooleanField(default=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="notifications.alertrulemodel",
                    ),
                ),
            ],
            options={
                "db_table": "notifications_alert_event",
                "indexes": [
                    models.Index(
                        fields=["rule", "wb_id", "triggered_at"],
                        name="notificatio_rule_id_be744d_idx",
                    )
                ],
            },
        ),
    ]
