# Generated by Django 5.2.17 on 2026-08-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SnapshotModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("wb_id", models.BigIntegerField(db_index=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rating", models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ("captured_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "analytics_snapshot",
                "indexes": [
                    models.Index(
                        fields=["wb_id", "captured_at"], name="analytics_s_wb_id_b2b9f7_idx"
                    )
                ],
            },
        ),
    ]
