# Generated by Django 5.2.17 on 2026-08-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snapshotmodel",
            name="wb_id",
            field=models.BigIntegerField(),
        ),
    ]
