# Generated by Django 5.2.17 on 2026-08-08 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchQueryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.CharField(db_index=True, max_length=200)),
                ("collected_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "catalog_search_query",
            },
        ),
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("wb_id", models.BigIntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=512)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rating", models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_query",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.searchquerymodel",
                    ),
                ),
            ],
            options={
                "db_table": "catalog_product",
                "indexes": [
                    models.Index(fields=["price"], name="catalog_pro_price_2d2a4c_idx"),
                    models.Index(fields=["sale_price"], name="catalog_pro_sale_pr_d20a45_idx"),
                    models.Index(fields=["rating"], name="catalog_pro_rating_67a263_idx"),
                    models.Index(fields=["reviews_count"], name="catalog_pro_reviews_90b1f9_idx"),
                ],
            },
        ),
    ]
