# Generated by Django 5.2.17 on 2026-08-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParseJobModel",
            fields=[
                ("task_id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("query", models.CharField(db_index=True, max_length=200)),
                ("status", models.CharField(db_index=True, default="pending", max_length=16)),
                ("created", models.PositiveIntegerField(default=0)),
                ("updated", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "catalog_parse_job",
                "indexes": [
                    models.Index(fields=["query", "status"], name="catalog_par_query_3f40e7_idx")
                ],
            },
        ),
    ]
