# Generated by Django 5.2.17 on 2026-08-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_parsejobmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parsejobmodel",
            name="query",
            field=models.CharField(max_length=200),
        ),
    ]
